name: Build ZerotixMod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Set up Gradle 6.8.3
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.8.3

      - name: Build
        run: gradle build --stacktrace

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZerotixMod
          path: build/libs/*.jar
