name: Build Zerotix Mod

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Setup Gradle 6.9.4
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 6.9.4

      - name: Build with Gradle
        run: gradle build --stacktrace

      - name: Upload mod jar
        uses: actions/upload-artifact@v4
        with:
          name: ZerotixMod
          path: build/libs/*.jar
